com:
  peng:
    name: Yk
    want: home
    fromMailAddr: 644710708@qq.com

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost/eureka/
  instance:
    statusPageUrlPath: /api.html

server:
  #主页
  homePage: api.html
  #端口
  port: 8081
  #上下文路径
  contextPath: /login
  #内置tomcat编码
  tomcat:
    uriEncoding: utf-8

spring:
  application:
    name: login
  http:
    converters:
      preferred-json-mapper: fastjson
  datasource:
    url: jdbc:mysql://localhost:3306/logindemo?useUnicode=true
    username: root
    password: admin
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    initialSize: 1
    minIdle: 3
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

  mail:
    host: smtp.qq.com #邮箱服务器地址
    username: 644710708@qq.com #用户名
    password: xkwadbnymuyzbbeb    #密码
    properties.mail.smtp.auth: true
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.socketFactory.port: 465
    properties.mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory
    properties.mail.smtp.socketFactory.fallback: false
    default-encoding: UTF-8
    port: 465

swagger:
  base-package: com.peng.controller

